# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANT_API_VERSION = 2

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.hostname = "cobbler"
  config.vm.define "cobbler" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.box_check_update = false
    
    config.vm.provider :virtualbox do |vm|
        vm.name = "cobbler"
        vm.memory = 2048
        vm.cpus = 1
    end
  end

  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  config.vm.network "private_network", ip: "1.1.1.2",
    virtualbox__intnet: "mgmt"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../cobbler.yaml"
  end

end
