# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = 2

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.hostname = "observer"
  config.vm.define "observer" do |cfg|
    cfg.vm.box = "pxe32"

    cfg.vm.provider :virtualbox do |vm|
        #TODO - change boot order, add netboot
        vm.name = "observer"
        vm.memory = 2048
        vm.cpus = 1
    end
  end

  #Net boot
  config.vm.network "private_network", type:"dhcp",
    virtualbox__intnet: "mgmt",
    nic_type: "virtio"   # For VLAN support
end
