# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.hostname = "observer"
  config.vm.define "observer" do |conf|
    conf.vm.box = "pxe32"

    conf.vm.provider :virtualbox do |vbox|
        #TODO - change boot order, add netboot
        vbox.name = "observer"
        vbox.memory = 2048
        vbox.cpus = 1
    end
  end
  #Net boot
  config.vm.network "private_network", type:"dhcp",
    virtualbox__intnet: "mgmnt",
    nic_type: "virtio"   # For VLAN support

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
end
